language: python
python:
- '2.7'
sudo: required
services:
- docker
before_install:
- curl -sSL https://get.docker.com/ > get_docker.sh
- sudo sh get_docker.sh
- sudo pip install -U docker-compose
- docker-compose -f docker/ci.docker-compose.yml pull
- docker-compose -f docker/ci.docker-compose.yml up -d
- docker exec docker_sfmflickrharvester_1 python -m unittest discover
install: pip install -r requirements/requirements.txt
script: python -m unittest discover
notifications:
  email:
  - justinlittman@gmail.com
  slack:
    secure: KGylYDnaV7cpmtzT6nslRKRXlpQTVlxVCx+osV5uKYTby07wmuybQtLIcWgRZZUDcGRXJPHCZORu+rvmJqRfI2Ase23zrA5mhgiifN0RirHxhGNf4jRh3qpHlsbzUmZf+YP2Jwu45eBotNfuxo7Ef0EC9nvB+ScbeVopR0k8G55KwDnLSjYEfjLbNhOoyoDANE+FcD0/nWFJ+ioIlFz20oNr3i8aozCqiUpOZdEJ9rNKCjmiFnnMgMluSxqK88jehIQ/HXmuS/QzneCd3q7dCCJ/HAp5X6jTFgt/K6vNgDmPzxyNqJcfZuPaTDkyfHa91a0zA8Hvx9le1q4YFSgR42QYmrtFeWURP3BfXH3IsiFuM5opepYpyLiIQVj8vjY7bg9hfh16m31DB4UvWkBc9FNOrmfYteeGhYT5My7FJVzCsX3L6fGLy33WxYj8+eH9SQ4exNTq8BoqzDpFREe5K+Ow/4wDrSVG3davNwigW1HhheoaRBvwBjUAPYzfZ+3YJBM81ZVMxZZbALHR9Xl/HVoG2PdmDEyV8qpihBbMbUT4p4/USkJdjQ7KYFhKuyLTJ5fDaCk9RDMNTGDfUlicmX54KbTmDRyKevxVvOzCzWCKWWqZ9V/SWMdVUekAp7iTno2GAb3/qANfJpb9E9ZtCPlQtgWllLbU1L7UEWRH7uw=
