sfmrabbit:
    image: rabbitmq@sha256:a5180a37b0baebb938ee9d12dd11eed64a909288d7f344e24771278f8a122367
    #RabbatMQ 3-management
    environment:
        - TZ=America/New_York
        - RABBITMQ_DEFAULT_USER=sfm_user
        - RABBITMQ_DEFAULT_PASS=password
sfmflickrharvester:
    image: gwul/sfm-flickr-harvester:dev
    links:
        - sfmrabbit:mq
    volumes:
        - "..:/opt/sfm-flickr-harvester"
    environment:
        - TZ=America/New_York
        - FLICKR_KEY
        - FLICKR_SECRET
    command: bash -c "pip install -r requirements/master.txt --upgrade && appdeps.py --port-wait mq:5672 && python flickr_harvester.py --debug=True service mq sfm_user password"
