sfmrabbit:
    image: rabbitmq:3-management
    environment:
        - RABBITMQ_DEFAULT_USER=sfm_user
        - RABBITMQ_DEFAULT_PASS=password
sfmflickrharvester:
    image: gwul/sfm-flickr-harvester:dev
    links:
        - sfmrabbit:mq
    volumes:
        - "..:/opt/sfm-flickr-harvester"
