sfmrabbit:
    image: rabbitmq@sha256:397382d2b222f3a298a6c74e93f348fb16f9a7fde2c02ba14122624d852daae3
    #RabbatMQ 3-management
    ports:
        - "15672:15672"
    restart: always
    environment:
        - TZ=America/New_York
        - RABBITMQ_DEFAULT_USER=sfm_user
        - RABBITMQ_DEFAULT_PASS=password
sfmflickrharvester:
    image: gwul/sfm-flickr-harvester:dev
    links:
        - sfmrabbit:mq
    volumes:
        - "..:/opt/sfm-flickr-harvester"
        - "../../sfm-utils:/opt/sfm-utils"
        - "../../warcprox:/opt/warcprox"
#    restart: always
    environment:
        - TZ=America/New_York
        - DEBUG=True
sfmflickrexporter:
    image: gwul/sfm-flickr-exporter:dev
    links:
        - sfmrabbit:mq
    volumes:
        - "..:/opt/sfm-flickr-harvester"
        - "../../sfm-utils:/opt/sfm-utils"
#    restart: always
    environment:
        - TZ=America/New_York
        - DEBUG=True
