sfmrabbit:
    image: rabbitmq:3-management
    ports:
        - "15672:15672"
    restart: always
    environment:
        - RABBITMQ_DEFAULT_USER=sfm_user
        - RABBITMQ_DEFAULT_PASS=password
sfmflickrharvester:
    #TODO: Change this to an image instead of build.
    build: ./master
    links:
        - sfmrabbit:mq
    restart: always
